name: Release
on:
  push:
    tags:
      - "*"
jobs:
  call-release-reusable:
    uses: a78devops/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project_name: expense-frontend
      npm_install: true
    secrets: inherit

